### ISSUE TITLE
No starknet found in window 1.1.0

### ISSUE THREAD

**Issue by hubsmoke** [argentlabs/argent-x#105]
I am trying to get 1.1.0 to work correctly with https://github.com/fracek/starknet-react-example but getting `Unhandled Rejection (Error): no starknet found in window`

However, according to console I do see starknet properly injected into the window object 

When attempting to test using the playground package, I see a similar issue:

![](https://cdn.discordapp.com/attachments/908663762150645770/922501702370873354/Screen_Shot_2021-12-20_at_9.52.14_AM.png)

On first load in a fresh tab, the above error pops up. After dismissing the error I can proceed without issue and sign transactions. I can even reload the page and the issue does not occur. However, if I open a new tab again I am greeted with the `no starknet found in window` error, which can be dismissed.

**Comment by janek26** [comment]
should be fixed now :-)
