### ISSUE TITLE
Would you consider changing the Ethereum mainnet to the starknet mainnet?

### ISSUE THREAD

**Issue by tuya77** [argentlabs/argent-x#1079]
In the discord of starknet, many new users are confused about the Ethereum main network. They are not sure whether it is the Ethereum main network or the starknet main network.
I suggest changing it to starknet main network.

**Comment by dhruvkelawala** [comment]
This is a really good suggestion. We are having discussion in the team and will update accordingly. Thank you

**Comment by simonheys** [comment]
This change will be in a forthcoming release, thanks for the suggestion
