### ISSUE TITLE
Request: Manually save json

### ISSUE THREAD

**Issue by aramanja** [argentlabs/argent-x#110]
If possible it would be great to be able to manually save the json. At the moment, if for some reason you don't save the json when prompted after adding a new wallet, it looks like there is no way to get the 'save json' window back other than adding yet another wallet

**Comment by delaaxe** [comment]
This is a good request, should be easy enough for a 'first contribution' pull request :)

**Comment by Kankan-0** [comment]
Hi @janek26 @delaaxe 
I would like to work on this issue.

What I planned and did :
1. Add another button in the settings page with the text "Download backup file" (can be changed the text/location if required)
2. When clicked, create the backup file using the existing code and download.

Let me know if I should go ahead and create a PR with the changes or if I need to modify something.

Thanks.

**Comment by Kankan-0** [comment]
Hi, Any update? Should I work on this issue ?

**Comment by janek26** [comment]
Hey @Kankan-0 ! Sorry for being late
Would be happy to review your PR implementing this feature! 
And yes, it should be a button in the settings page and when clicked it'd be cool to use code that already exists to download the keyfile, but in case that's not possible it's also okay to add a new branch for it

**Comment by Kankan-0** [comment]
Hi @janek26  created this PR. Please review and let me know if any changes are required.
