### ISSUE TITLE
Account contract incompatible with Cairo v0.10

### ISSUE THREAD

**Issue by minkyn** [argentlabs/argent-x#1231]
With Cairo upgraded to v0.10.0, two new functions are required in the account contract: `__validate__` and `__validate_declare__`, causing the current Argent-X wallet accounts not able to work with the latest Starknet CLI in `invoke` and `declare`.

Is there a plan to upgrade the Account implementation soon?

**Comment by janek26** [comment]
yes :) We're close to finishing this, as we just released https://github.com/0xs34n/starknet.js/releases/tag/v4.7.0
The contracts are also already finished: https://github.com/argentlabs/argent-contracts-starknet/ 

I think it'll take us maybe 2 more weeks

**Comment by minkyn** [comment]
Sorry to ask again on this issue.

Once the v1 account contract has finished, what shall we do as the end users? Will the implementation of all existing accounts be automatically upgraded, or the users need to do something on the wallet for that to happen?

We are about to the launch our own dApp using the accounts deployed by Argent-X, and now we have to use some older APIs (e.g. "declare" changes from v0 to v1) to accommodate with the v0 accounts. Things will break if the account upgrades would happen automatically. We would like the process to be user triggerable so that we can update the APIs at the same time.
