### ISSUE TITLE
Error when adding a new token to wallet

### ISSUE THREAD

**Issue by 0xHyoga** [argentlabs/argent-x#1233]
Hi! I keep getting this error when adding a new token to the Argentx wallet:

![image](https://user-images.githubusercontent.com/97303883/192061197-e68d48b5-c63f-4b9b-aa49-7d2eb8cbd7ec.png)

Any idea what could be happening?

**Comment by 0xHyoga** [comment]
pasting the log here:

`
  "stack": "U: Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:95)\nUnknown location (pc=0:47)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:121)\n\nError in the called contract (0x14be76cce31783fab1cfb4c8be244e38c0465f7cfec9cdd150705cce919a290):\nEntry point 0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e not found in contract with class hash 0x60c4cefed931d32c11d4661a31df251b5a50217f11e37a51ce66b6e0602709a.\n    at re.<anonymous> (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:130316)\n    at V (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:127035)\n    at Object.next (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:126304)\n    at fe (chrome-extension://dlcobpjiigpikoobohmab'ehhmhfoodbb/main.js:109:125835)",
  "message": "Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:95)\nUnknown location (pc=0:47)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:121)\n\nError in the called contract (0x14be76cce31783fab1cfb4c8be244e38c0465f7cfec9cdd150705cce919a290):\nEntry point 0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e not found in contract with class hash 0x60c4cefed931d32c11d4661a31df251b5a50217f11e37a51ce66b6e0602709a.",
  "name": "U",
  "errorCode": "StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT"
}
No stack trace
`

I'm using ArgentX on Brave browser

**Comment by janek26** [comment]
The token you added: https://testnet.starkscan.co/contract/0x14be76cce31783fab1cfb4c8be244e38c0465f7cfec9cdd150705cce919a290#read-contract

doesn't implement the expected ERC20 interface
instead of implementing `balanceOf` it implements `balance_of`

we should check that and deny adding these kind of tokens

**Comment by 0xHyoga** [comment]
Great to know. Thanks!

**Comment by 0xHyoga** [comment]
I'm re-opening this, i keep getting this same error sorry.

`
v4.8.1

{
  "stack": "U: Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:95)\nUnknown location (pc=0:47)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:121)\n\nError in the called contract (0x57ce5ef7a5cd3f76ab8f0cd47c901d77d95fd461e1514e5b49dcba0c7cb85fa):\nEntry point 0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e not found in contract with class hash 0x60c4cefed931d32c11d4661a31df251b5a50217f11e37a51ce66b6e0602709a.\n    at re.<anonymous> (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:130316)\n    at V (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:127035)\n    at Object.next (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:126304)\n    at fe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:109:125835)",
  "message": "Error at pc=0:25:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:95)\nUnknown location (pc=0:47)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:142)\nUnknown location (pc=0:121)\n\nError in the called contract (0x57ce5ef7a5cd3f76ab8f0cd47c901d77d95fd461e1514e5b49dcba0c7cb85fa):\nEntry point 0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e not found in contract with class hash 0x60c4cefed931d32c11d4661a31df251b5a50217f11e37a51ce66b6e0602709a.",
  "name": "U",
  "errorCode": "StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT"
}
No stack trace
`

I modified the ERC20 contract to be exactly like the Solidity but i keep gettting this same error .

**Comment by 0xHyoga** [comment]
![image](https://user-images.githubusercontent.com/97303883/192167320-b3d86259-3346-4358-82ce-a7a373539861.png)

Same issue as before when adding a custom token.

**Comment by janek26** [comment]
Did you read and understand my previous message?

> Am 25.09.2022 um 23:54 schrieb 0xHyoga ***@***.***>:
> 
> 0x57ce5ef7a5cd3f76ab8f0cd47c901d77d95fd461e1514e5b49dcba0c7cb85fa
