### ISSUE TITLE
[UI] Collectibles quantity gets compressed when collectible name is too long

### ISSUE THREAD

**Issue by NicolasMassart** [argentlabs/argent-x#1279]
When the collectible mame is too long, the number in the black circle on the bottom right corner of the collectible is compressed  and touching the collectible name and the circle is just a small ellipse.
See screenshot bellow.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/4677568/193905731-547ad4af-de9f-41a7-b907-e989d4aca9a1.png">

**Comment by simonheys** [comment]
Thank you for taking the time to report this issue, it will be addressed in a future release
