### ISSUE TITLE
add a request for checking if token has already been added to the wallet

### ISSUE THREAD

**Issue by retroboydev** [argentlabs/argent-x#1299]
Let's say, I have a button `Add FooToken to Wallet`, and when the user clicks on it, a dialog box appears for adding this token:
```
window.starknet.request({
  type: 'wallet_watchAsset',
  params: {
    type: 'ERC20',
    options: {
      address: '0xFoo'
    }
  }
}).then((e)=> {console.log(e)}) //waiting for the user to finish working with the dialog
```
However, if the token has already been added to the wallet, this request obviously returns `false`. But this is the only way to check if a token has been added (as far as I can see in the code). It would be nice to have a similar method to check this without opening a dialog box if the token has not been added yet (for example, to hide this button). Something like this:

```
window.starknet.request({
  type: 'wallet_doesAssetExist', // the first thing that came to mind, feel free to suggest another name
  params: {
    type: 'ERC20',
    options: {
      address: '0xFoo'
    }
  }
}).then((e)=> {console.log(e)}) // true / false
```

I skimmed through the code, and it looks pretty easy to add this stuff, so I can do it if you like the idea and it correlates with your roadmap.

**Comment by qingsky7** [comment]
good
