### ISSUE TITLE
Wrong injected starknet on window 

### ISSUE THREAD

**Issue by dan-ziv** [argentlabs/argent-x#160]
In my app, I'm using starknet.js as one of the dependencies so in my `package.json` file, `starknet` is on version `2.7.1`.
In `@argent/get-starknet`, `starknet` is on version `2.5.0` (as a peer dependency).
For some reason, the injected starknet on the window got the peer dependency version instead of mine, i.e., pulls starknet from the `/dist` in  `@argent/get-starknet` and not from my app's bundle.

**Comment by janek26** [comment]
I just checked this:
The `@argent/get-starknet` bundle doesn't contain an instance of starknet. Therefore it must source starknet from your install. It uses the normal Node module resolve method.
If you keep having this problem please make sure to delete all node_modules folders and start from a fresh install. It should pickup the version that's available, no matter what.
