### ISSUE TITLE
Timeout when sending wallet_switchStarknetChain request

### ISSUE THREAD

**Issue by florian-bellotti** [argentlabs/argent-x#1615]
I could not succeed to configure the wallet_switchStarknetChain request. I always receive a `Error: Timeout` error.

Here is a sample of code i am using. This code is triggered just after the connection to a ArgentX account. 
```ts
    getStarknet() // from get-starknet
      .getAvailableWallets()
      .then((wallets) => {
        wallets
          .filter((wallet) => wallet.id === 'argentX')[0]
          .request({
            type: 'wallet_switchStarknetChain',
            params: { chainId: constants.StarknetChainId.TESTNET2 },
          });
      });
```

I think that the error is triggered here, but I do not understand why.

requestMessageHandlers.ts
```ts 
  const req = await Promise.race([
    waitForMessage("REQUEST_ADD_CUSTOM_NETWORK_RES", 1000),
    waitForMessage("REQUEST_ADD_CUSTOM_NETWORK_REJ", 1000),
  ])
```

**Comment by dhruvkelawala** [comment]
The params is incorrect. It expects `chainId` to be one of `SN_MAIN`, `SN_GOERLI` or `SN_GOERLI2`. So your code will change to 

```    getStarknet() // from get-starknet
      .getAvailableWallets()
      .then((wallets) => {
        wallets
          .filter((wallet) => wallet.id === 'argentX')[0]
          .request({
            type: 'wallet_switchStarknetChain',
            params: { chainId: 'SN_GOERLI2' },
          });
      });```

**Comment by dhruvkelawala** [comment]
Added a better solution. But will be available in next release. With this PR, you can continue using constants.StarknetChainId.TESTNET2

**Comment by pei-zklend** [comment]
Just wanted to follow up on this, currently I am also having a timed out error when running wallet_switchStarknetChain request.

I am running 

```
.request({
          type: "wallet_switchStarknetChain",
          params: {
            chainId: encodeShortString("SN_MAIN"),
          },
        })
```

to switch to the mainnet network but seems to be having issues with mainnet only. Any idea why?
