### ISSUE TITLE
Bug with 2 submitted transactions and rejecting the first

### ISSUE THREAD

**Issue by 0xEniotna** [argentlabs/argent-x#1654]
Hey, I didnt find a related issue.
There seems to be a bug in that situation:

1.  Submit a first tx, do not accept or reject it and close the window (so the waiting-for-acceptance tx will still appear if we open again argentX).
2. Submit a second transaction (a new argentX popup appears)
3. Reject the first one

Rejecting the first one seems to somehow automatically accept and trigger the second tx.

**Comment by dhruvkelawala** [comment]
That's intended. We create a Transaction with a nonce X. When you create another transaction it's created with nonce X+1.
If you submit second transaction with nonce X+1, it will fail.
