### ISSUE TITLE
not the same address with bravvos? 

### ISSUE THREAD

**Issue by viponedream** [argentlabs/argent-x#1959]
which address is correct?

1, create new wallet in bravvos,  and copy the recovery words to argentx,  it generate the different address.
2, create new wallet in argent-x,  and copy the recovery words to bravvos,  it say not support.

**Comment by raminsherwani** [comment]
i have same problem but in both side no one answer !!!

**Comment by YoleYu** [comment]
They didn't follow BIP39. A Ethereum layer2 project has not a matched address with the main Eth network.
