### ISSUE TITLE
Why will handling fees be deducted if the transaction fails?

### ISSUE THREAD

**Issue by demoManito** [argentlabs/argent-x#2118]
<img width="348" alt="image" src="https://github.com/argentlabs/argent-x/assets/27986239/bdef5781-2ab9-4d84-a147-07b1c78a2720">
Network fee was not refunded to me

**Comment by demoManito** [comment]
<img width="343" alt="image" src="https://github.com/argentlabs/argent-x/assets/27986239/7b873052-c59b-4fea-9412-dd9e443dd7d2">
All are reverted

**Comment by demoManito** [comment]
I'm so broken

**Comment by SoloJiang** [comment]
So am I

**Comment by demoManito** [comment]
> So am I

你需要预留扣除手续费的数量，就可以成功提现了

**Comment by vanenshi** [comment]
i also face this problem

**Comment by demoManito** [comment]
> i also face this problem
> 

you need to reserve the amount for deducting transaction fees in order to successfully withdraw the transfer
