### ISSUE TITLE
Can't see balance of custom token

### ISSUE THREAD

**Issue by oscarwroche** [argentlabs/argent-x#2149]
I deployed a new ERC20 token and minted myself some tokens - however the token balance is never displayed in my wallet even though the transfers are (see attached pictures). What's going on ?

![Screenshot 2024-11-19 at 18 50 10](https://github.com/user-attachments/assets/c1ac5412-2df2-4553-9032-024a2f15d283)
![Screenshot 2024-11-19 at 18 49 59](https://github.com/user-attachments/assets/d0f47e7b-1ac4-4c8e-8822-b7154a4bc96d)

**Comment by Angiepeck22** [comment]
Hello @oscarwroche 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ALP07638
Please see the link below to our dedicated support line:
[Alpha Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Kiari26** [comment]
Potential scam. Don’t click on any link

**Comment by Athensmo** [comment]
Hello @oscarwroche 
Thank you for submitting your issue to this repository! A maintainer will be here shortly to triage and review.
In the meantime, please double-check that you have provided all the necessary information to make this process easy! Any information that can help save additional round trips is useful! We currently aim to give initial feedback within two business days. If this does not happen, feel free to leave a comment.
Please keep an eye on how this issue will be labeled, as labels give an overview of priorities, assignments and additional actions requested by the maintainers:

"Priority" labels will show how urgent this is for the team.
"Status" labels will show if this is ready to be worked on, blocked, or in progress.
"Need" labels will indicate if additional input or analysis is required.

Finally, remember to use the official Decentralized Dapps Protocol to initiate a chat with the support team to get immediate support via [our Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat 💬 icon at the bottom of the page to get started.
