### ISSUE TITLE
Disconnect feature

### ISSUE THREAD

**Issue by delaaxe** [argentlabs/argent-x#262]
- Users should be able to add a disconnect button from the their dapp
- Should be in the test dapp as an example

**Comment by jgresham** [comment]
taking a look

**Comment by janek26** [comment]
should be just a change in the example dapp
jediswap already has this: https://app.testnet.jediswap.xyz/#/swap

**Comment by jgresham** [comment]
After disconnecting, and then reconnecting, should the user be prompted with this again? (This is not how JediSwap works currently. JediSwap reconnects without requiring this.)

![reconnect](https://user-images.githubusercontent.com/3721291/153601838-b6b2780c-b01f-4043-af2b-c4c71fd1e7cf.png)

Related, but could be in a new issue, I think with #90 implemented, allowing disconnect to a dapp from extension, there needs to be an event passed to the dapp to know that the user disconnected the dapp from the extension.

**Comment by juniset** [comment]
Yes, if the user disconnects and reconnects from a dapp he should see the "Connect to a dapp" prompt.

Agree that when the user disconnects from a dapp in the extension an event should be passed to the dapp. We already have the `accountsChanged` [event](https://github.com/argentlabs/argent-x/blob/df7c174d26c435c6d951d6d9d4fd5ebbd082d761/packages/extension/src/inpage/index.ts#L132) so we should use the same event but with an empty array. I'll create a separate issue.

**Comment by delaaxe** [comment]
@juniset We should probably implement the rest of the standard events like 'chainChanged', 'connect', 'disconnect': https://docs.metamask.io/guide/ethereum-provider.html#events

**Comment by jgresham** [comment]
It seems like the dapp whitelist and if a dapp is connected are separate concepts in current metamask specs.

**Comment by delaaxe** [comment]
I agree with @jgresham here, on JediSwap clicking on `disconnect` doesn't remove it from the whitelist

**Comment by delaaxe** [comment]
yes this should make more sense

**Comment by dhruvkelawala** [comment]
> I agree with @jgresham here, on JediSwap clicking on `disconnect` doesn't remove it from the whitelist

Hi, I am leading frontend at JediSwap and I can confirm that we are not "disconnecting" from ArgentX in a proper way. We are just doing a soft disconnect, meaning just removing the currently connected account from the frontend. 

We were waiting for a method on Starknet Window Object to implement this method, such as `window.starknet.disconnect()` which can support removing from the whitelist.

**Comment by janek26** [comment]
should be solved by https://github.com/argentlabs/argent-x/pull/378
please reopen if that's not the case
