### ISSUE TITLE
Name Account

### ISSUE THREAD

**Issue by janek26** [argentlabs/argent-x#263]
As a user I want to be able to change the name of my account, to label them.

AC:
- Name changes do not need to be stored in backup files.
- I can change the displayed name of an account.

**Comment by jgresham** [comment]
taking a look

**Comment by jgresham** [comment]
Made some progress on this today.

1. Account names are saved in local storage using (networkId, address) as the key.
2. Changes the Profile icon using the account name
3. If the user tries to set a null account name, then "Account #" is used
4. Names are not saved in backup file


https://user-images.githubusercontent.com/3721291/153716498-1a36fa0d-2d1e-4da5-832b-54cd03e1aaa7.mp4

https://user-images.githubusercontent.com/3721291/153716500-4104c97d-978d-4c95-b4cc-d95caedc1520.mp4

**Comment by juniset** [comment]
Hey @jgresham , that's great and exactly how it was intended to be implemented.
