### ISSUE TITLE
Emit event when a dapp is disconnected

### ISSUE THREAD

**Issue by juniset** [argentlabs/argent-x#292]
When the user disconnects a dapp, the extension should pass an event to the dapp.

We should use the `accountsChanged` event but pass an empty array, see https://github.com/argentlabs/argent-x/blob/df7c174d26c435c6d951d6d9d4fd5ebbd082d761/packages/extension/src/inpage/index.ts#L132

See #262 for more context.

**Comment by jgresham** [comment]
It doesn't look like the metamask api docs support what we were hoping to do. We would need to pass the `accountsChanged` (with empty array) event to only the dapp that we are disconnecting from. Also, for argent-x I don't see the ability to pass a message from the extension to a specific dapp/tab/host. Am I missing anything?

**Comment by jasonzhouu** [comment]
actually Metamask do send message from extension to specific tab

https://github.com/MetaMask/metamask-extension/blob/19098f7d69c5f1ca7f2cfd31f7179e0a44d7db2f/app/scripts/metamask-controller.js#L3486

**Comment by juniset** [comment]
Closed by #378
