### ISSUE TITLE
Cannot create account on mainnet - error 500

### ISSUE THREAD

**Issue by wickles** [argentlabs/argent-x#294]
I'm trying to switch to mainnet and create an account but it fails with an error, status code 500. Is this expected behavior? I am able to create a functioning account on the testnet without issue. 

System config: Macbook Pro M1 Pro (2021), macOS 12.2, Brave 1.35.101 arm64

<img width="318" alt="Screen Shot 2022-02-14 at 11 09 56 AM" src="https://user-images.githubusercontent.com/4229542/153930500-658e7e32-e06c-463e-97c7-4cd00a53ed5f.png"> <img width="314" alt="Screen Shot 2022-02-14 at 11 10 09 AM" src="https://user-images.githubusercontent.com/4229542/153930505-749bbf49-5749-4a15-a25e-19f23eb15f67.png">

**Comment by jgresham** [comment]
What version of the extension do you have? Check extension versions with `brave://extensions/` in browser

**Comment by wickles** [comment]
Extension version 2.2.2

**Comment by juniset** [comment]
Hey @wickles , thanks for flagging this! 

After checking it turns out that the `ArgentAccount.cairo` contract was no longer whitelisted on StarkNet mainnet (for now Starkware whitelists the contracts that can be deployed to mainnet). 

They fixed it and it should now work.
