### ISSUE TITLE
Accounts changed event is not fired

### ISSUE THREAD

**Issue by fracek** [argentlabs/argent-x#295]
I noticed that even if my application subscribes to the `accountsChanged` event (using `starknet.on('accountsChanged', cb)`, my callback is never called.

**Comment by jgresham** [comment]
@fracek there is an example dapp with this functionality working. Here is the example code: 
https://github.com/argentlabs/argent-x/blob/c7540a82dcbd34776a6a1bad79d2451f0c26482a/packages/dapp/src/services/wallet.service.ts#L97

**Comment by juniset** [comment]
Closed by #378
