### ISSUE TITLE
Timeout when signing transactions

### ISSUE THREAD

**Issue by wraitii** [argentlabs/argent-x#309]
We see briq users occasionally getting Timeout errors. The symptoms show up as follows:
<img width="532" alt="Capture d’écran 2022-02-17 à 18 21 27" src="https://user-images.githubusercontent.com/1927071/154536121-4faf147d-b600-4ebb-a71d-850612829d5e.png">

So far as I can tell, this is coming from [this line](https://github.com/argentlabs/argent-x/blob/main/packages/extension/src/inpage/index.ts#L39) in the code. I'm not sure if it's a network issue that doesn't get forwarded, or an Argent-specific timeout. Regardless, it seems wrong that this fails with a string instead of an Error.

**Comment by delaaxe** [comment]
https://github.com/argentlabs/argent-x/pull/327

**Comment by wraitii** [comment]
I don't have much more information currently unfortunately. I'm hoping the switch to errors will give me better information.

I can re-open this when I have more information, or just leave it open for a few more days to try and get data?

**Comment by delaaxe** [comment]
The new version should now give better information on errors. Let me know if you encounter this error again
