### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by delaaxe** [argentlabs/argent-x#311]
Generally, good codebases always use the same words to refer to the same concepts. It makes things quicker to understand and easier to look up and navigate.

Currently, we're using:
- Both `keystore` and `backup` to refer to the same concept. We should pick one and stick to it.
- Both `whitelist` and `pre-authorization` interchangeably, there should be only one.
- `Wallet` / `Account` / `Signer`, which should eventually match StarkNet's nomenclature.

In addition, it would be ideal if the naming in code matches what's displayed in UI and otherwise communicated to users, but this may not always be strictly possible.

**Comment by jgresham** [comment]
Wallet/Account distinction in their docs https://starknet.io/docs/hello_starknet/account_setup.html

Any other docs with nomenclature for this?

**Comment by delaaxe** [comment]
pretty much. I'll do this after the currently opened PRs are merged

**Comment by delaaxe** [comment]
Done on v3 branch
