### ISSUE TITLE
Ledger Nano S support integration: unable to detect HID device

### ISSUE THREAD

**Issue by jcaporossi-ledger** [argentlabs/argent-x#359]
Hello,

 I am currently working on Ledger Nano S integration. I would like to understand why I cannot see Nano S device as HID device when I call `await navigator.hid.requestDevice({filters:[]});` from the console ? Same for `await navigator.hid.getDevices()`.
Tried to figure out where it might come from (extension permission ?), but I am running out of ideas...
Any clue ?
Thanks,
Kind regards,
Jerome

**Comment by janek26** [comment]
try `await navigator.hid.requestDevice({filters:[]}); ` from a tab. It's a known issue that extensions don't support HID, therefore you need to make the requests from a dedicated tab.

**Comment by jcaporossi-ledger** [comment]
> try `await navigator.hid.requestDevice({filters:[]}); ` from a tab. It's a known issue that extensions don't support HID, therefore you need to make the requests from a dedicated tab.

Thx for your answer, and yes this is finally what I do....
