### ISSUE TITLE
add chainId to StarknetWindowObject and implement `chainChanged` listener

### ISSUE THREAD

**Issue by dhruvkelawala** [argentlabs/argent-x#376]

**Comment by dhruvkelawala** [comment]
I'll try and create a PR for this

**Comment by jgresham** [comment]
I'd be willing to implement. lmk if you want me to @dhruvkelawala

**Comment by dhruvkelawala** [comment]
@jgresham If you want, you can review this code and maybe make a PR for some other issue on this repo.
