### ISSUE TITLE
Not enough to import old wallets

### ISSUE THREAD

**Issue by elenkadelf** [argentlabs/argent-x#397]
Good afternoon, I am testing various projects with Argent X StarkNet Wallet and encountered the following error when loading an older version of Wallet 
~\Desktop\argent-extension-v2.3.0
Error
Manifest file is missing or unreadable
Manifest could not be loaded.
I need to install the old version based on your instructions, because now I don't know how it will affect my participation in various projects with the change of the old address to the new one

**Comment by aziat240275** [comment]
Good afternoon. Don’t tell me what’s happening yesterday normally, the argent x wallet opened and worked, but today I opened it and I can’t log in, I’m trying to restore via json file, it gives me such an entry and that’s it. I don’t know what to do, all my activity was connected with that wallet, and now you’ll do a new one and start all over again. Please tell me what to do, it’s a shame, I just managed to trade NFT there, I had 1925 test tokens on my balance.
![ShooterScreenshot-1-12-03-22](https://user-images.githubusercontent.com/96283531/158005468-35ad8bf2-d335-49d1-8d12-a1d75e232ba2.png)

**Comment by aziat240275** [comment]
I'm trying to download the old wallet from the link, and it says the file is damaged.
![ShooterScreenshot-2-12-03-22](https://user-images.githubusercontent.com/96283531/158006733-598a546d-be9b-426f-98a8-efc07135313e.png)

**Comment by xnatasx** [comment]
Hi,

I am stuck on Step 3:
https://github.com/argentlabs/argent-x/blob/develop/docs/Upgrade_v3.md

I am also trying to install the old wallet through Zip in Dev Mode.
Then I get:
_Could not unzip extension for install._

I have also tried to unzip it and load the Package folder. Then I instead get message about Manifest error.

I have tried in Chrome and Brave.
I have downloaded again.
I have restarted PC.
I have uninstalled Ad blocker.
I have 7zip installed.
I'm on Windows 11...

**Comment by xnatasx** [comment]
Solved: Had to go deeper into the folder, to Dist.

**Comment by AnatoliyKonstantinov777** [comment]
Hello! You have come up with a very unfortunate and bad system for accessing the wallet.
https://www.argent.xyz/faq/
I used your testnet wallet https://app.testnet.jediswap.xyz/
I spent about 1 month testing.
Today I turned on the computer and there is no access to the wallet.
Of course, I deleted the file a long time ago, but I have a password. But for some reason your wallet is not restored by password.
There is no such function, and requires the creation of a new wallet.
I uninstalled and installed a new wallet.
My old wallet address: 0x039f29f00b9df8cce5ca1db4568d22d23121090561b5c67e8def6067cf9cc822
What should I do to regain access to it???
I know the wallet address, I know the password.
https://www.argent.xyz/faq/
 
Sincerely, Anatoly Konstantinov.

**Comment by janek26** [comment]
Hey @xnatasx, great to see you made it and migrated your funds! Thanks to your feedback we added the missing step to the document you linked, so future users won't run into this kinda issue, thanks again!


Wallet transaction history is not considered an asset and therefore can't be migrated. I made a post on when it makes sense to migrate funds (basically just NFTs you really like or because you've coded your own ERC20 which already has value to you): https://github.com/argentlabs/argent-x/issues/400#issuecomment-1067635605

Test tokens can simply be minted again at https://argentlabs.github.io/argent-x/

**Comment by xnatasx** [comment]
No, I was able to restore old one, and send some test assets over to the new one.
Most I was unable to since, I don't find my way around Voyager... to see token and now how to send them from there, since I hadn't added all into the ArgentX app.

**Comment by elenkadelf** [comment]
The problem is that I can not install an old version of the wallet in the browser application, it does not accept them
would like to solve this problem...it creates some difficulties, but given this fact I understand something.... in the connection of all test networks)_)) but I also understand that the guys did not plan to solve these issues at this stage ....

**Comment by elenkadelf** [comment]
> Эй, @xnatasx, рад видеть, что вы сделали это и перенесли свои средства! Благодаря вашим отзывам мы добавили недостающий шаг в документ, который вы связали, поэтому будущие пользователи не столкнутся с этой проблемой, еще раз спасибо!
> 
> История транзакций кошелька не считается активом и поэтому не может быть перенесена. Я сделал сообщение о том, когда имеет смысл переносить средства (в основном только NFT, которые вам действительно нравятся, или потому, что вы закодировали свой собственный ERC20, который уже имеет для вас ценность): [#400 (комментарий)](https://github.com/argentlabs/argent-x/issues/400#issuecomment-1067635605)
> 
> Тестовые токены могут быть просто отчеканены снова на https://argentlabs.github.io/argent-x/

Guys, but how should we be...because we've worked with other test networks...

**Comment by milongkmt** [comment]
https://github.com/argentlabs/argent-x/pull/686#pullrequestreview-989020118
