### ISSUE TITLE
I uninstalled and installed a new wallet.

### ISSUE THREAD

**Issue by AnatoliyKonstantinov777** [argentlabs/argent-x#400]
Hello! You have come up with a very unfortunate and bad system for accessing the wallet.
https://www.argent.xyz/faq/
I used your testnet wallet https://app.testnet.jediswap.xyz/
I spent about 1 month testing.
Today I turned on the computer and there is no access to the wallet.
Of course, I deleted the file a long time ago, but I have a password. But for some reason your wallet is not restored by password.
There is no such function, and requires the creation of a new wallet.
I uninstalled and installed a new wallet.
My old wallet address: 0x039f29f00b9df8cce5ca1db4568d22d23121090561b5c67e8def6067cf9cc822
What should I do to regain access to it???
I know the wallet address, I know the password.
https://www.argent.xyz/faq/
 
Sincerely, Anatoly Konstantinov.

**Comment by AnatoliyKonstantinov777** [comment]
Ok

**Comment by AnatoliyKonstantinov777** [comment]
Ok

**Comment by janek26** [comment]
there is no value in starknet goerli and starknet mainnet yet. There are no official ether bridges, and especially for goerli starknet testnet there is no value. This includes your transaction history

So if you have troubles restoring your v2 wallet, just create a new v3 wallet and let us know if you have any issues with that! 🙂 
In case you want to keep some asset (like Briq nft) make sure to follow https://github.com/argentlabs/argent-x/blob/develop/docs/Upgrade_v3.md#what-does-it-mean-as-an-argent-x-user

It makes no sense to recover most ERC20 funds as most of them are simply mintable. And there's no concept of migrating a transaction history
