### ISSUE TITLE
Recover Private Key from exported JSON

### ISSUE THREAD

**Issue by anistark** [argentlabs/argent-x#401]
Trying to recover the private key from exported json file using the password.

I've tried using [keyethereum](https://github.com/ethereumjs/keythereum) but it throws error. 

Is there any example or existing libraries to do this?

**Comment by janek26** [comment]
it's an ethers.js backkup at the core, so ethers.js should be able to do it! :)

**Comment by anistark** [comment]
> it's an ethers.js backkup at the core, so ethers.js should be able to do it! :)

Could you please point me to the ethersjs function which does this?

**Comment by anistark** [comment]
> > it's an ethers.js backkup at the core, so ethers.js should be able to do it! :)
> 
> Could you please point me to the ethersjs function which does this?

Nvm. Found it. Thanks for the pointer.

**Comment by rvorias** [comment]
> > > it's an ethers.js backkup at the core, so ethers.js should be able to do it! :)
> > 
> > 
> > Could you please point me to the ethersjs function which does this?
> 
> Nvm. Found it. Thanks for the pointer.

Could you share how you fixed it?
