### ISSUE TITLE
Problem downloading a backup file

### ISSUE THREAD

**Issue by elenkadelf** [argentlabs/argent-x#403]
Nothing happens when a backup file is loaded..
I press as usual to select a file on the PC, I choose...that's it...
and lacks the ability to open the wallet in a separate full-fledged window
![Screenshot_4](https://user-images.githubusercontent.com/36508492/159075802-9c16d022-bb70-4029-b241-9f317e6958b0.png)
.

**Comment by elenkadelf** [comment]
In general, I decided not to bother... because there is no way to solve it... I created a new purse and tested it again... let's see how this version of the purse works

**Comment by dhruvkelawala** [comment]
We updated the wallet, this issue is no longer relevant.
