### ISSUE TITLE
Create a wallet with Argent X on the locally running devnet?

### ISSUE THREAD

**Issue by ccarnino** [argentlabs/argent-x#417]
Hello all! 
How can I connect and create a wallet with Argent X on the locally running devnet?

I have a devnet running correctly on my machine. I go to ArgentX extension, select localhost network, tap + to create a wallet since there is none, but I always get "RangeError: Maximum call stack size exceeded".

I am trying to interact with a contract deployed on devnet, so I need to have ArgentX setup on localhost to interact with it. 

Am I doing something wrong?
Thanks!

**Comment by tangtj** [comment]
I also got the same error.

**Comment by microbecode** [comment]
I'm getting "illegal method signature" when trying to create an account (deploy the account contract) to devnet. Using the latest devnet (0.1.19) and ArgentX 3.0
