### ISSUE TITLE
Click address jump to wrong page in the explorer.

### ISSUE THREAD

**Issue by huagegege** [argentlabs/argent-x#497]
If an account address started with '0',click address in the wallet than jump to the wrong account page,the '0' in the front the address was dismissed.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/29689127/162683136-951a886e-9542-4074-878d-3ee1a2e0c79c.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/29689127/162683386-40b6e9d1-6752-4231-9456-4b54eb46fe1d.png">

**Comment by juniset** [comment]
It is the same contract. Because StarkNet uses `felt` that are 251 bits instead of 256, addresses are sometimes prefixed with a leading 0. Both corresponds to the same address.

**Comment by huagegege** [comment]
> It is the same contract. Because StarkNet uses `felt` that are 251 bits instead of 256, addresses are sometimes prefixed with a leading 0. Both corresponds to the same address.

I have try it in the scan and it shows different account
