### ISSUE TITLE
Update `deploying` status in AccountListScreen after deployed

### ISSUE THREAD

**Issue by delaaxe** [argentlabs/argent-x#547]
Accounts stay with "Deploying..." state indefinitely until clicking on the account.

The background should catch a "deployment done" event and update the account state accordingly, even while the UI is closed.

**Comment by dhruvkelawala** [comment]
I think this is already fixed, isn't it @simonheys?

**Comment by simonheys** [comment]
> I think this is already fixed, isn't it @simonheys?

Yes we've done some work that should resolve this one
