### ISSUE TITLE
[UI] Token balance overflow

### ISSUE THREAD

**Issue by sdlyy** [argentlabs/argent-x#692]
Hi there 👋🏻 

Simple UI issue with the overflown token balance. Reactive font adjustment or something, dunno 😄

Screen below. No issue guidelines were mentioned, but I'm open to provide you with more information if needed.

Short Spec:
Macbook Pro M1 2020
Opera GX Browser
Full-size window (not the full screen tho)

<img width="359" alt="image" src="https://user-images.githubusercontent.com/67391475/171172520-4e21ad4b-207f-482a-b233-4207ed7084b6.png">

**Comment by dhruvkelawala** [comment]
Thanks for reporting it. We will fix it.
