### ISSUE TITLE
The new project hasn't stabilized yet. Will the used wallet be emptied because of a BUG?

### ISSUE THREAD

**Issue by yingnengd** [argentlabs/argent-x#761]
The new project hasn't stabilized yet. Will the used wallet be emptied because of a BUG?

**Comment by janek26** [comment]
I don't get this comment and it makes no sense.

I answered your other question in #760 

**Starknet is Alpha, expect breaking changes like this one and don't bridge funds you can not lose**

We also only migrated Goerli to the new version, which is an alpha test network


Maines to follow in ~2 weeks.
