### ISSUE TITLE
Older version of starknet.js is used for `call_contract`

### ISSUE THREAD

**Issue by Arcticae** [argentlabs/argent-x#843]
Hello - i am having an issue when using argentx and trying to catch the errors from the client-app side, the bundled js seems to use an older version of starknet.js to execute the call, thus preventing me from catching the error.

I created a simple repro here:
https://codesandbox.io/s/react-typescript-forked-69omrc?file=/src/App.tsx

**Comment by janek26** [comment]
hey man, I'll make sure to update starknet.js before our next release!

**Comment by Arcticae** [comment]
Thank you for your response :) I will try it out after the release

**Comment by janek26** [comment]
should be available next week Tuesday fyi

**Comment by dhruvkelawala** [comment]
Seems like this is done. Closing it.

**Comment by Arcticae** [comment]
![image](https://user-images.githubusercontent.com/34059895/177117485-f1b45573-7784-4910-89c7-88aa254e30d2.png)
This is still an issue for me - see the screenshot & codesandbox example
