### ISSUE TITLE
Why can't the wallet address I just generate cannot get the test ETH token from faucet?

### ISSUE THREAD

**Issue by FrankFan** [argentlabs/argent-x#854]
1. I downloaded and installed the ArgentX extension from chrome store
2. I created a new Account in ArgentX
3. I got my new address: `0x03D95fe4F8dDFdD232Fc1513A045f07703FAff83E0AF4A24C1B600b04B07B6d7`
4. I wanna get some test ETH Token from a [faucet](https://goerli-faucet.pk910.de/), but some error happened.
![image](https://user-images.githubusercontent.com/1589433/176887352-43e52c66-7b1f-400b-bc7f-450724ce2684.png)

Why does this address look so strange and not the same length as the Ethereum address？

Is there any documentation to solve this prblem ?

**Comment by FrankFan** [comment]
and this faucet reported the same problem: https://goerlifaucet.com/

![image](https://user-images.githubusercontent.com/1589433/176888044-a7b5ee5f-95c7-4a59-8b8e-a6eddebbc6e1.png)

**Comment by janek26** [comment]
thanks for the report. It's an issue with the faucet
I'll contact Starkware on this to fix it.

**Comment by FrankFan** [comment]
@janek26  thank you for your quickly reply. 

I want to confirm that the address generated by ArgentX wallet is correct? 
why the address length is 66, but MastMask address's length is 42 ?

What is the difference between ArgentX and MetaMask?

**Comment by janek26** [comment]
ah, I just noticed you linked to a goerli Ethereum faucet!

Argent X is made to work with Starknet only
please use the starknet goerli etc faucet: https://faucet.goerli.starknet.io
