### ISSUE TITLE
List of connected sites

### ISSUE THREAD

**Issue by sol-inherent** [argentlabs/argent-x#90]
It would be nice to see a list of all the sites that are connected to an account and manage connections individually. Currently, it is only possible to reset all connections.

**Comment by delaaxe** [comment]
This is a good request, should be easy enough for a 'first contribution' pull request :)

**Comment by Kankan-0** [comment]
Hi @janek26 
I actually wanted to work on this too. Can you probably give me some example sites where I can connect my account and test it?

**Comment by janek26** [comment]
sure thing

you can use 
https://argentlabs.github.io/argent-x/
https://www.myswap.xyz/#/
https://mintsquare.io
https://github.com/starkware-libs/starkgate-frontend

to list a few

**Comment by janek26** [comment]
@Kankan-0 how is it going?
Should I take over?

**Comment by Kankan-0** [comment]
Hi @janek26 , I haven't had the time to work on this one. You can take it over.
