### ISSUE TITLE
Can't recover wallet on Linux

### ISSUE THREAD

**Issue by parseb** [argentlabs/argent-x#94]
I might be totally wrong as this can be a particularity of my setup. 

Can anyone actually drop a file in that space?
In order to drag _starknet-backup.json_ you likely need to click somewhere else, which closes the dialogue and makes restarting the process a necessity. The process itself (browsing, selecting the backup file) does nothing for me, but not working is less annoying than "promising" me a drag-and-drop experience and not delivering. (test environment: Ubuntu / Chromium / v1.1.0) 

![image](https://user-images.githubusercontent.com/5999852/146692110-93e51e09-7881-48be-bee8-b91d0ea6c62c.png)

**Comment by arya4291** [comment]
I can confirm I have the same issues using Ubuntu & Brave

**Comment by aramanja** [comment]
I can confirm I have the same issues when using Ubuntu & Brave. The drag & drop function and json restoration works fine for me on Windows 10 & Brave.

**Comment by janek26** [comment]
it seems like drag and drop is an issue for ubuntu, please let me know if you have any way of fixing this.
Restoring after that should work just fine.

**Comment by parseb** [comment]
The drag&drop functionality is OS correlated behavior. It also happens for metamask for example. 
I do not think that in itself is a bug. 

Suggested First step:
- Reproduce wallet recovery dis-functionality on ubuntu/brave or ubuntu/chromium.

**Comment by jgresham** [comment]
Looks like the most recent bug report to chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1027558
Haven't found one for linux/OS

**Comment by janek26** [comment]
Hey @jgresham, thanks for looking into this. We already thought of a simple solution, basically opening the setup process in a dedicated tab, in case we detect ubuntu/linux.
This could also transform into the default behavior when we decide to support ledger, they need a dedicated tab anyways to connect to their devices.

**Comment by janek26** [comment]
I can publish more around this soon, and create a few new issues to the project, but it's already late here :D

**Comment by jgresham** [comment]
Found a workaround here that works now!

1. Open extension
2. Right click "Inspect" (Chrome devtools window should open)
3. Import file now and chrome should not close extension when you focus on file selector

**Comment by gergold** [comment]
Another workaround is to open the extension in a tab using its url:
`chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html`
and navigate to "Restore Wallet".

Anyway, we are working on a button in the Settings that will open the extension in a new tab
